platform :ios, '13.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

def add_flipper_pods!
  version = '~> 0.33.1'
  pod 'FlipperKit', version, :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitLayoutPlugin', version, :configuration => 'Debug'
  pod 'FlipperKit/SKIOSNetworkPlugin', version, :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitUserDefaultsPlugin', version, :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitReactPlugin', version, :configuration => 'Debug'
end
# Post Install processing for Flipper
def flipper_post_install(installer)
  installer.pods_project.targets.each do |target|
    if target.name == 'YogaKit'
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.1'
      end
    end
  end
end

target 'SvipeAuthExample' do
  # Pods for SvipeAuthExample
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/callinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga', :modular_headers => true

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'react-native-svipe-auth', :path => '../..'
  
  pod 'SvipeKit', :path => '../../..'
  
  pod 'CertKit',  :path => '../../../CertKit'
  
  
  #pod 'SvipeKit', :git => 'https://github.com/svipe/SvipeKit.git', :branch => :master

  pod 'Credstore',  :path => '../../../Credstore'#
  #pod 'Credstore', :git => 'https://github.com/svipe/svipe-ios-credstore.git', :branch => :master

  pod 'PotentCodables',  :path => '../../../Credstore/PotentCodables/'
  #pod 'PotentCodables', :git => 'https://github.com/svipe/PotentCodables.git', :branch => :master
  pod 'PotentASN1',  :path => '../../../Credstore/PotentCodables/'
  #pod 'PotentASN1', :git => 'https://github.com/svipe/PotentCodables.git', :branch => :master
  pod 'PotentCBOR',  :path => '../../../Credstore/PotentCodables/'
  #pod 'PotentCBOR', :git => 'https://github.com/svipe/PotentCodables.git', :branch => :master
  pod 'PotentJSON',  :path => '../../../Credstore/PotentCodables/'
  #pod 'PotentJSON', :git => 'https://github.com/svipe/PotentCodables.git', :branch => :master
   
  pod 'Shield',  :path => '../../../Credstore/Shield'
  #pod 'Shield', :git => 'https://github.com/svipe/Shield.git', :branch => :master
  pod 'ShieldCrypto',  :path => '../../../Credstore/Shield'
  #pod 'ShieldCrypto', :git => 'https://github.com/svipe/Shield.git', :branch => :master
  pod 'ShieldSecurity',  :path => '../../../Credstore/Shield'
  #pod 'ShieldSecurity', :git => 'https://github.com/svipe/Shield.git', :branch => :master
  pod 'ShieldPKCS',  :path => '../../../Credstore/Shield'
  #pod 'ShieldPKCS', :git => 'https://github.com/svipe/Shield.git', :branch => :master
  pod 'ShieldX500',  :path => '../../../Credstore/Shield'
  #pod 'ShieldX500', :git => 'https://github.com/svipe/Shield.git', :branch => :master
  pod 'ShieldX509',  :path => '../../../Credstore/Shield'
  #pod 'ShieldX509', :git => 'https://github.com/svipe/Shield.git', :branch => :master
  pod 'ShieldOID',  :path => '../../../Credstore/Shield'
  #pod 'ShieldOID', :git => 'https://github.com/svipe/Shield.git', :branch => :master

  pod 'OrderedDictionary',  :path => '../../../Credstore/OrderedDictionary'
  #pod 'OrderedDictionary', :git => 'https://github.com/svipe/OrderedDictionary.git', :branch => :master

  
  pod 'SwiftQRScanner', :git => ‘https://github.com/vinodiOS/SwiftQRScanner’
  #pod 'WebAuthnKit',  :path => '../WebAuthnKit-iOS'
  
  #pod 'WebAuthnKit', :git => 'https://github.com/svipe/WebAuthnKit-iOS.git', :branch => :develop
  #pod 'NFCPassportReader', :git => 'https://github.com/svipe/NFCPassportReader.git', :branch => :master
  pod 'NFCPassportReader',:path => '../../../NFCPassportReader'
  pod 'FaceVerifier',  :path => '../../../FaceVerifier'
  #pod 'FaceVerifier', :git => 'https://github.com/svipe/FaceVerifier.git', :branch => :master
  #pod 'SwiftyTesseract' , :path => '../SwiftyTesseract'
  pod 'SwiftyTesseract', :git => 'https://github.com/svipe/SwiftyTesseract.git', :branch => :master
  
  #pod 'CommonKit', :git => 'https://github.com/svipe/CommonKit.git', :branch => :master
  pod 'CommonKit',  :path => '../../../CommonKit'
  
  pod 'BluetoothKit', :path => '../../../BluetoothKit'
  #pod 'BluetoothKit', :git => 'https://github.com/svipe/'BluetoothKit.git', :branch => :master

   pod 'Realm',:modular_headers => true
   pod 'DeepLinkKit',:modular_headers => true

  use_native_modules!
  
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  add_flipper_pods!
  post_install do |installer|
    flipper_post_install(installer)
  end
end
